### ISSUE TITLE
Blank screen on login

### ISSUE THREAD

**Issue by NeonPaul** [NeonPaul/shack#2]
"right cache was cleared and I logged back into the site, after i submitted my credentials the screen goes white and the page remains as ../shack/. The main message board page can be accessed by pressing F5 to refresh the page"

Chrome on windows

**Comment by coolinkuk** [comment]
This issue is the same for all computers I've signed in with. Including Windows 7 running Chrome, Windows 10 running Chrome and Edge, and iOS8 running Safari

**Comment by coolinkuk** [comment]
This issue also happens when a post has been made from Win10/Chrome (I've not tested any others). It can be corrected by reloading the ../shack/ page.

**Comment by NeonPaul** [comment]
https://github.com/NeonPaul/abode/issues/9
